### ISSUE TITLE
(US #8) Visualizar FAQ - Perguntas frequentes

### ISSUE THREAD

**Issue by ecmeirelles** [fga-gpp-mds/2016.2-SAS_FGA#25]
- 1 Ponto

**Comment by allanpereiras** [comment]
Acho que não tem teste unitário, vai ser só uma página estática @ecmeirelles

**Comment by ecmeirelles** [comment]
Verdade @allanpereiras , eu só copiei e colei e nem percebi que esse era só estática mesmo e não tem teste unitário
