### ISSUE TITLE
Remodelar campos (dropdowns, data e hora)

### ISSUE THREAD

**Issue by ecmeirelles** [fga-gpp-mds/2016.2-SAS_FGA#45]
**US 12**
- Issue #14 
- 3 Pontos

**Comment by suzukijessica** [comment]
@allanpereiras você não tinha começado a fazer essa tarefa?

**Comment by gutorc92** [comment]
@suzukijessica Comecei, mas não consegui fazer na época

**Comment by allanpereiras** [comment]
Osh se a pessoa responder pelo telegram vem na conta do gustavo ahauahau

**Comment by gutorc92** [comment]
@allanpereiras ë porq fui eu que configurei o bot, eu acho
