### ISSUE TITLE
(US #13) Como administrador, selecionar uma engenharia para a reserva

### ISSUE THREAD

**Issue by suzukijessica** [fga-gpp-mds/2016.2-SAS_FGA#90]
- [ ] Selecionar um curso da FGA (Engenharia, Eng de Energia, Eng Automotiva, Eng Aeroespacial, Eng de Software, Eng Eletrônica)

- 2 Pontos

**Comment by gutorc92** [comment]
@suzukijessica Cade a galera do usuario?
